# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # CHANGE BEFORE DEPLOYING, RUN `rake secret`
  secret_key_base: 97c04abb20ee51d7f039b18a4aefb92bf7ffc666725d99ee8a9a70d9ed63d0b70d319b0c273094eac64254d39032fb4623a3bad1438ab6ccd3e34a1a6ef53e24
  yelp_consumer_key : <%= ENV["YELP_CONSUMER_KEY"] %>
  yelp_consumer_secret : <%= ENV['YELP_CONSUMER_SECRET'] %>
  yelp_token :  <%= ENV['YELP_TOKEN'] %>
  yelp_token_secret : <%= ENV['YELP_TOKEN_SECRET'] %>

  tw_api_key : <%= ENV['TW_API_KEY']%>
  tw_api_secret : <%= ENV['TW_API_SECRET']%>
  fb_app_id : <%= ENV['FB_APP_ID']%>
  fb_app_secret : <%= ENV['FB_APP_SECRET']%>

test:
  # CHANGE BEFORE DEPLOYING, RUN `rake secret`
  secret_key_base: dba00ec026768565d9bbe33e22e690a32d875a7719d7a963e4e6f3e3bb167085f4711a9bbf2c04b1ec10d96b45dca9afe2ba1d7a6e1774ac87aeaa372451da6b
  yelp_consumer_key : <%= ENV["YELP_CONSUMER_KEY"] %>
  yelp_consumer_secret : <%= ENV['YELP_CONSUMER_SECRET'] %>
  yelp_token :  <%= ENV['YELP_TOKEN'] %>
  yelp_token_secret : <%= ENV['YELP_TOKEN_SECRET'] %>

  tw_api_key : <%= ENV['TW_API_KEY']%>
  tw_api_secret : <%= ENV['TW_API_SECRET']%>
  fb_app_id : <%= ENV['FB_APP_ID']%>
  fb_app_secret : <%= ENV['FB_APP_SECRET']%>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yelp_consumer_key : <%= ENV["YELP_CONSUMER_KEY"] %>
  yelp_consumer_secret : <%= ENV['YELP_CONSUMER_SECRET'] %>
  yelp_token :  <%= ENV['YELP_TOKEN'] %>
  yelp_token_secret : <%= ENV['YELP_TOKEN_SECRET'] %>

  tw_api_key : <%= ENV['TW_API_KEY']%>
  tw_api_secret : <%= ENV['TW_API_SECRET']%>
  fb_app_id : <%= ENV['FB_APP_ID']%>
  fb_app_secret : <%= ENV['FB_APP_SECRET']%>


